---
abstract: 'Statistics enhancement package for ORLite'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: ORLite::Statistics
name: ORLite-Statistics
no_index:
  directory:
    - inc
    - t
requires:
  ORLite: 1.25
  Statistics::Basic: 1.6600
  perl: 5.8.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/ORLite-Statistics
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/ORLite-Statistics
version: 0.02
